version: '3'

tasks:
  build:
    aliases:
      - b
    cmds:
      - go build

  clean:
    aliases:
      - c
    cmds:
      - rm tt

  clean-build:
    aliases:
      - cb
    cmds:
      - task: c
      - task: b

  run:
    aliases:
      - r
    cmds:
      - task: b
      - ./tt {{.CLI_ARGS}}

  test:
    aliases:
      - t
    cmds:
      - go test -v ./... -timeout 15s